version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t $DOCKER_REPO .
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker push $DOCKER_REPO



